apiVersion: apps/v1
kind: Deployment
metadata:
  name: appfastfood-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appfastfood
  template:
    metadata:
      labels:
        app: appfastfood
    spec:
      containers:
        - name: appfastfood
          image: vitoravanco/appfastfood:2.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: appfastfood-configmap
            - secretRef:
                name: app-secret
          readinessProbe:
            httpGet:
              path: /healthCheck   # Rota de verificação de saúde do seu aplicativo
              port: 8080            # Porta em que o seu aplicativo está ouvindo
            initialDelaySeconds: 10
            periodSeconds: 5
